export interface PoolPlayer {
  id: string;
  name: string;
  position: string;
  tier: 'T1' | 'T2' | 'T3' | 'T4';
  currentScore: number;
  isInField: boolean;
}

export const AVAILABLE_PLAYERS: PoolPlayer[] = [
  {
    id: 'p1',
    name: 'Scottie Scheffler',
    position: 'T1',
    tier: 'T1',
    currentScore: -12,
    isInField: true,
  },
  {
    id: 'p2',
    name: 'Rory McIlroy',
    position: 'T1',
    tier: 'T1',
    currentScore: -10,
    isInField: true,
  },
  {
    id: 'p3',
    name: 'Jon Rahm',
    position: 'T1',
    tier: 'T1',
    currentScore: -9,
    isInField: false,
  },
  {
    id: 'p4',
    name: 'Viktor Hovland',
    position: 'T1',
    tier: 'T1',
    currentScore: -8,
    isInField: true,
  },
  {
    id: 'p5',
    name: 'Xander Schauffele',
    position: 'T2',
    tier: 'T2',
    currentScore: -7,
    isInField: true,
  },
  {
    id: 'p6',
    name: 'Patrick Cantlay',
    position: 'T2',
    tier: 'T2',
    currentScore: -7,
    isInField: false,
  },
  {
    id: 'p7',
    name: 'Max Homa',
    position: 'T2',
    tier: 'T2',
    currentScore: -6,
    isInField: true,
  },
  {
    id: 'p8',
    name: 'Jordan Spieth',
    position: 'T2',
    tier: 'T2',
    currentScore: -6,
    isInField: true,
  },
  {
    id: 'p9',
    name: 'Tony Finau',
    position: 'T3',
    tier: 'T3',
    currentScore: -5,
    isInField: true,
  },
  {
    id: 'p10',
    name: 'Collin Morikawa',
    position: 'T3',
    tier: 'T3',
    currentScore: -5,
    isInField: true,
  },
  {
    id: 'p11',
    name: 'Sam Burns',
    position: 'T3',
    tier: 'T3',
    currentScore: -4,
    isInField: false,
  },
  {
    id: 'p12',
    name: 'Hideki Matsuyama',
    position: 'T3',
    tier: 'T3',
    currentScore: -4,
    isInField: true,
  },
  {
    id: 'p13',
    name: 'Sungjae Im',
    position: 'T4',
    tier: 'T4',
    currentScore: -3,
    isInField: true,
  },
  {
    id: 'p14',
    name: 'Cameron Young',
    position: 'T4',
    tier: 'T4',
    currentScore: -3,
    isInField: true,
  },
  {
    id: 'p15',
    name: 'Tommy Fleetwood',
    position: 'T4',
    tier: 'T4',
    currentScore: -2,
    isInField: false,
  },
  {
    id: 'p16',
    name: 'Russell Henley',
    position: 'T4',
    tier: 'T4',
    currentScore: -2,
    isInField: true,
  },
  {
    id: 'p17',
    name: 'Corey Conners',
    position: 'T4',
    tier: 'T4',
    currentScore: -1,
    isInField: true,
  },
  {
    id: 'p18',
    name: 'Sahith Theegala',
    position: 'T4',
    tier: 'T4',
    currentScore: -1,
    isInField: true,
  },
  {
    id: 'p19',
    name: 'Tom Kim',
    position: 'T4',
    tier: 'T4',
    currentScore: 0,
    isInField: false,
  },
  {
    id: 'p20',
    name: 'Justin Rose',
    position: 'T4',
    tier: 'T4',
    currentScore: 0,
    isInField: true,
  },
];
