-- Populate Schedule table with tournament data
INSERT INTO "Schedule" ("id", "tournamentId", "tournamentName", "isActive", "createdAt", "updatedAt")
VALUES
  (gen_random_uuid(), 'R2025006', 'Sony Open in Hawaii', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025002', 'The American Express', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025004', 'Farmers Insurance Open', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025005', 'AT&T Pebble Beach Pro-Am', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025003', 'WM Phoenix Open', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025007', 'The Genesis Invitational', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025540', 'Mexico Open at VidantaWorld', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025010', 'Cognizant Classic in The Palm Beaches', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025009', 'Arnold Palmer Invitational presented by Mastercard', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025011', 'THE PLAYERS Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025475', 'Valspar Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025020', 'Texas Children''s Houston Open', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025041', 'Valero Texas Open', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025014', 'Masters Tournament', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025012', 'RBC Heritage', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025522', 'Corales Puntacana Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025018', 'Zurich Classic of New Orleans', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025019', 'THE CJ CUP Byron Nelson', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025480', 'Truist Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025553', 'Myrtle Beach Classic', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025033', 'PGA Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025021', 'Charles Schwab Challenge', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025023', 'the Memorial Tournament presented by Workday', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025032', 'RBC Canadian Open', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025026', 'U.S. Open', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025034', 'Travelers Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025524', 'Rocket Mortgage Classic', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025030', 'John Deere Classic', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025541', 'Genesis Scottish Open', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025518', 'ISCO Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025100', 'The Open Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025472', 'Barracuda Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025525', '3M Open', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025013', 'Wyndham Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025027', 'FedEx St. Jude Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025028', 'BMW Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025060', 'TOUR Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025464', 'Procore Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025468', 'Ryder Cup', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025054', 'Sanderson Farms Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025527', 'Baycurrent Classic', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025554', 'Black Desert Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025457', 'World Wide Technology Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025528', 'Butterfield Bermuda Championship', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025493', 'The RSM Classic', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025478', 'Hero World Challenge', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'R2025551', 'Grant Thornton Invitational', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); 